service:
- docker

language: java
jdk: openjdk8

addons:
  apt:
  packages:
  - jq
  - bash
  - curl
  - sudo
  - lsof
  - unzip
  - wget
  - ibxml2-utils
  - docker-ce
  - python-pip    

install: true
before_install:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 80

script:
- bash gradlew clean build

after_script:
- bash gradlew --stop

cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
